apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: remotesecret-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remotesecret-operator@sha256:16de2293955d09e75c0a93cce0c7f358f20c8809f95bda69e6b35a972d591c89
        name: container-image
        resources: {}
status: {}
