apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: remotesecret-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remotesecret-operator@sha256:c1b66225e516c55c8b67c91f1cbbcd254f7e5dd8292ede58db0ba706a66a2793
        name: container-image
        resources: {}
status: {}
