apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: remotesecret-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remotesecret-operator@sha256:d8d3e4d91442979e502be30ec1cc37d939ef5704589626c70568ea790aa89f24
        name: container-image
        resources: {}
status: {}
