apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: remotesecret-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remotesecret-operator@sha256:35678ec8494e1c06745697ddc370be6e1a31439874cb4c1a955bb7d714bbb96e
        name: container-image
        resources: {}
status: {}
