apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: remotesecret-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remotesecret-operator@sha256:39daf906e60ac9aa2b111758b065fb40be253a182bcd3536caf8a77547e26d37
        name: container-image
        resources: {}
status: {}
