apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: remotesecret-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: remotesecret-operator
    app.kubernetes.io/part-of: remotesecret
  name: remotesecret-operatormj0s
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: remotesecret-operator
    weight: 100
status: {}
