apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: remotesecret-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: remotesecret-operator
    app.kubernetes.io/part-of: remotesecret
  name: remotesecret-operator
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: remotesecret-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: remotesecret-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remotesecret-operator@sha256:52c66c80b28760a824d91e6635326c27fdee39ceffeb5cf804d55627c04f5e4c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
