apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: remotesecret-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: remotesecret-operator
    app.kubernetes.io/part-of: remotesecret
  name: remotesecret-operator
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: remotesecret-operator
status:
  loadBalancer: {}
