apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: remote-secret
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remote-secret@sha256:de57d89b04862b9c1566269fcab11c21d2426152d1c91c5dfdc2c3a08eb2ad5f
        name: container-image
        resources: {}
status: {}
